name: Update Frontmatter
on:
  pull_request:
  push:
permissions: {}
jobs:
  update-seo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run update-seo.mjs
        run: node ./scripts/update-seo.mjs
      - uses: autofix-ci/action@v1
        with:
          commit-message: "chore: auto-update frontmatter [skip ci]"
